// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfJjWaO1ZGNvoEpdMVOZiRiIO5IQnNZl4',
    appId: '1:995857913091:web:c1a370edc38b3f7a9dc536',
    messagingSenderId: '995857913091',
    projectId: 'fir-test-117',
    authDomain: 'fir-test-117.firebaseapp.com',
    storageBucket: 'fir-test-117.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS_ZxXrv9sTPMlp0UhM_nLrOHSKnH5Eks',
    appId: '1:995857913091:android:b1549ad4833034599dc536',
    messagingSenderId: '995857913091',
    projectId: 'fir-test-117',
    storageBucket: 'fir-test-117.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8_K85Cvx52J6AEGUZwf-AuiCljyyTkkM',
    appId: '1:995857913091:ios:c97c63e9b8d676969dc536',
    messagingSenderId: '995857913091',
    projectId: 'fir-test-117',
    storageBucket: 'fir-test-117.appspot.com',
    iosClientId: '995857913091-5e8ld7en5nhl815od395agtuqbg97bce.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentest117',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8_K85Cvx52J6AEGUZwf-AuiCljyyTkkM',
    appId: '1:995857913091:ios:c97c63e9b8d676969dc536',
    messagingSenderId: '995857913091',
    projectId: 'fir-test-117',
    storageBucket: 'fir-test-117.appspot.com',
    iosClientId: '995857913091-5e8ld7en5nhl815od395agtuqbg97bce.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentest117',
  );
}
